"""Agregar filas para confirmacion de mail

Revision ID: 38291e1434a3
Revises: 9c8e3e8933e5
Create Date: 2022-01-30 11:32:15.849094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38291e1434a3'
down_revision = '9c8e3e8933e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_on')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'registered_on')
    # ### end Alembic commands ###
